General:
  Reload-Permission: "ajm.reload"
  Permission-Message: "&cYou do not have permission to use this command."
  Reloaded-Message: "&aYou have successfully reloaded &7AdvancedJoinMessages&a!"
  Remove-Default-Message: true
Messages:
  Join:
    Enabled: true
    Text:
      - '< &7[&a+&7] %luckperms_prefix%><&8%player_name%>< &7joined the server!>'
      - '< &c&lAdd more lines!>< &7Click me for help!>'
    ids:
      '0':
        '0':
          Hover:
            Enabled: true
            Text: "&7Click here to say &e'Hey'&7 to &e%player_name%&7!"
          Click:
            Enabled: true
            Type: "RUN_COMMAND"
            Data: "/tell %player_name% Hey"
        '1':
          Hover:
            Enabled: true
            Text: '&7Click here to open a &eURL&7!'
          Click:
            Enabled: true
            Type: "OPEN_URL"
            Data: "https://www.google.com"
        '2':
          Hover:
            Enabled: true
            Text: '&7Click here to suggest &esomething&7...'
          Click:
            Enabled: true
            Type: "SUGGEST_COMMAND"
            Data: "/kill"
      '1':
        '0':
          Hover:
            Enabled: false
            Text: ""
          Click:
            Enabled: false
            Type: ""
            Data: ""
        '1':
          Hover:
            Enabled: true
            Text: '&7Click me for help on configuration!'
          Click:
            Enabled: true
            Type: "OPEN_URL"
            Data: "https://github.com/CoachLuck/AdvancedJoinMessages"
  Leave:
    Enabled: true
    Text:
      - '< &7[&c-&7] %luckperms_prefix%><&8%player_name%>< &7left the server!>'
      - '< &c&lAdd more lines!>< &7Click me for help!>'
    ids:
      '0':
        '0':
          Hover:
            Enabled: true
            Text: "&7Click here to say &e'Bye'&7 to &e%player_name%&7!"
          Click:
            Enabled: true
            Type: "RUN_COMMAND"
            Data: "/tell %player_name% Hey"
        '1':
          Hover:
            Enabled: true
            Text: '&7Click here to open a &eURL&7!'
          Click:
            Enabled: true
            Type: "OPEN_URL"
            Data: "https://www.google.com"
        '2':
          Hover:
            Enabled: true
            Text: '&7Click here to suggest &esomething&7...'
          Click:
            Enabled: true
            Type: "SUGGEST_COMMAND"
            Data: "/kill"
      '1':
        '0':
          Hover:
            Enabled: false
            Text: ""
          Click:
            Enabled: false
            Type: ""
            Data: ""
        '1':
          Hover:
            Enabled: true
            Text: '&7Click me for help on configuration!'
          Click:
            Enabled: true
            Type: "OPEN_URL"
            Data: "https://github.com/CoachLuck/AdvancedJoinMessages"