# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#Messages:                                                                          #
#  Join:                                                                            #
#    Enabled: true                                                                  #
#    Text: '<&7[&a+&7] %luckperms_prefix%><&8%player_name%><&7joined the server!>'  #
#    ids:                                                                           #
#      '0':                                                                         #
#        # Enabled: true | false (Enable|Disable hover for the element)             #
#        # Text: The text to be displayed on hover (Supports placeholders)          #
#        Hover:                                                                     #
#          Enabled: true                                                            #
#          Text: '&7Click here to send a &aTPA request &7to &e%player%'             #
#                                                                                   #
#        # Enabled: true | false (Enable|Disable click for the element)             #
#        # Type: "SUGGEST_COMMAND" | "RUN_COMMAND" | "OPEN_URL"                     #
#        # Data: Command | URL (%player% as placeholder for playername)             #
#        #       If this is set to command. Include the '/'                         #
#        Click:                                                                     #
#          Enabled: true                                                            #
#          Type: "RUN_COMMAND"                                                      #
#          Data: "/tell %player% Hey"                                               #
#                                                                                   #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#     INFORMATION       INFORMATION     INFORMATION     INFORMATION     INFORMATION #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# 'ids'                                                                             #
#     1. These are defined by text inbetween '<' & '>'                              #
#     2. These must start at 0, Here is an example showing if it was in the main    #
#        Text for a message - Text: "<id: '0'><id: '1'><id: '2'>"                   #
#        etc.                                                                       #
#     3. You can use any color codes and these will allow placeholders              #
#     4. Space between two ids is ignored, for example "<%player%><has joined!>"    #
#        would look like "PlayerNamehas joined". To add spaces include them within  #
#        the '<>' tags.                                                             #
#                                                                                   #
# 'Remove-Default-Message': whether or not to display the default join message      #
#                           This only matters if you disable Join/Leave message     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
General:
  Reload-Permission: "ajm.reload"
  Permission-Message: "&cYou do not have permission to use this command."
  Reloaded-Message: "&aYou have successfully reloaded &7AdvancedJoinMessages&a!"
  Remove-Default-Message: true
Messages:
  Join:
    Enabled: true
    Text: '<&7[&a+&7] %luckperms_prefix%><&8%player_name%>< &7joined the server!>'
    ids:
      '0':
        Hover:
          Enabled: true
          Text: "&7Click here to say &e'Hey'&7 to &e%player%&7!"
        Click:
          Enabled: true
          Type: "RUN_COMMAND"
          Data: "/tell %player% Hey"
      '1':
        Hover:
          Enabled: true
          Text: '&7Click here to open a &eURL&7!'
        Click:
          Enabled: true
          Type: "OPEN_URL"
          Data: "https://www.google.com"
      '2':
        Hover:
          Enabled: true
          Text: '&7Click here to suggest &esomething&7...'
        Click:
          Enabled: true
          Type: "SUGGEST_COMMAND"
          Data: "/kill"
  Leave:
    Enabled: true
    Text: '<&7[&a+&7] %luckperms_prefix%><&8%player_name%>< &7left the server!>'
    ids:
      '0':
        Hover:
          Enabled: true
          Text: "&7Click here to say &e'Bye' &7to &e%player%&7!"
        Click:
          Enabled: true
          Type: "RUN_COMMAND"
          Data: "/tell %player% Bye!"
      '1':
        Hover:
          Enabled: true
          Text: '&7Click here to open a &eURL&7!'
        Click:
          Enabled: true
          Type: "OPEN_URL"
          Data: "https://www.google.com"
      '2':
        Hover:
          Enabled: true
          Text: '&7Click here to suggest &esomething&7...'
        Click:
          Enabled: true
          Type: "SUGGEST_COMMAND"
          Data: "/kill"